# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lb_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flb_server.proto\"\"\n\x0f\x42ooleanResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x03\x43O2\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\"D\n\x08Humidity\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\"1\n\tPollution\x12\x11\n\tpollution\x18\x01 \x01(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x32l\n\nLB_service\x12/\n\rSendPollution\x12\n.Pollution\x1a\x10.BooleanResponse\"\x00\x12-\n\x0cSendHumidity\x12\t.Humidity\x1a\x10.BooleanResponse\"\x00\x32p\n\x0eServer_service\x12/\n\rSendPollution\x12\n.Pollution\x1a\x10.BooleanResponse\"\x00\x12-\n\x0cSendHumidity\x12\t.Humidity\x1a\x10.BooleanResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lb_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOLEANRESPONSE._serialized_start=19
  _BOOLEANRESPONSE._serialized_end=53
  _CO2._serialized_start=55
  _CO2._serialized_end=92
  _HUMIDITY._serialized_start=94
  _HUMIDITY._serialized_end=162
  _POLLUTION._serialized_start=164
  _POLLUTION._serialized_end=213
  _LB_SERVICE._serialized_start=215
  _LB_SERVICE._serialized_end=323
  _SERVER_SERVICE._serialized_start=325
  _SERVER_SERVICE._serialized_end=437
# @@protoc_insertion_point(module_scope)
